# vim:ts=2:sw=2:et:ai:sts=2
---
# =============================================================================
# Reusable defaults and templates for geoip role.
# =============================================================================

geoip__enable: false
